import { Colors } from '@/constants/theme';
import { store } from '@/store/store';
import { useFonts } from 'expo-font';
import { Stack } from 'expo-router';
import * as SplashScreen from 'expo-splash-screen';
import * as SystemUI from 'expo-system-ui';
import React, { useEffect } from 'react';
import { Provider } from 'react-redux';

export default function RootLayout() {
  const [loaded] = useFonts({
    'SpaceGrotesk-Regular': require('../assets/fonts/SpaceGrotesk-Regular.otf'),
    'SpaceGrotesk-Medium': require('../assets/fonts/SpaceGrotesk-Medium.otf'),
    'SpaceGrotesk-Bold': require('../assets/fonts/SpaceGrotesk-Bold.otf'),
  });

  SystemUI.setBackgroundColorAsync(Colors.dark.background);

  // // Run mount effects (prevent auto-hide and set background color)
  // useEffect(() => {
  //   let mounted = true;
  //   async function prepare() {
  //     try {
  //       await SplashScreen.preventAutoHideAsync();
  //     } catch {
  //       // ignore
  //     }
  //     try {
  //       await SystemUI.setBackgroundColorAsync(Colors.dark.background);
  //     } catch {
  //       // ignore
  //     }
  //   }
  //   if (mounted) prepare();
  //   return () => {
  //     mounted = false;
  //   };
  // }, []);

  // // Hide the splash screen only once fonts are loaded.
  useEffect(() => {
    if (loaded) {
      SplashScreen.hideAsync();
    }
  }, [loaded]);

  if (!loaded) {
    return null;
  }

  // Global stack transition options. Use a subtle fade transition for enter/exit.
  // We cast to `any` for developer ergonomics while types are generated by Expo.
  const stackOptions: any = {
    headerShown: false,
    // Use fade animation and explicit transition specs for smoother exit/enter.
    animation: 'slide_from_right',
    transitionSpec: {
      open: { animation: 'timing', config: { duration: 500 } },
      close: { animation: 'timing', config: { duration: 500 } },
    },
    cardStyleInterpolator: ({ current }: any) => ({
      cardStyle: { opacity: current.progress },
    }),
    // detachPreviousScreen: false,
  };

  return (
    <Provider store={store}>
    <Stack screenOptions={stackOptions}>
      <Stack.Screen name="screens/OnboardingScreen" />
      <Stack.Screen name="screens/MapScreen" />
      <Stack.Screen name="screens/SettingsScreen" />
    </Stack>
    </Provider>
  );
}
  