import { useFonts } from 'expo-font';
import { Stack } from 'expo-router';
import * as SplashScreen from 'expo-splash-screen';
import { useEffect } from 'react';

// Prevent the splash screen from auto-hiding before asset loading is complete.
SplashScreen.preventAutoHideAsync();

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [loaded, error] = useFonts({
    'SpaceGrotesk-Regular': require('../assets/fonts/SpaceGrotesk-Regular.otf'),
    'SpaceGrotesk-Medium': require('../assets/fonts/SpaceGrotesk-Medium.otf'),
    'SpaceGrotesk-Bold': require('../assets/fonts/SpaceGrotesk-Bold.otf'),
  });

  useEffect(() => {
    if (loaded || error) {
      SplashScreen.hideAsync();
    }
  }, [loaded, error]);

  if (!loaded && !error) {
    return null;
  }

  // Global stack transition options. We use a subtle fade transition for enter/exit
  // and cast to `any` for a smooth developer experience while types are generated by Expo.
  const stackOptions: any = {
    headerShown: false,
    // animation options supported by react-navigation / expo-router: 'fade', 'slide_from_right', etc.
    animation: 'slide_from_right',
    detachPreviousScreen: false,
  };

  return (
      <Stack screenOptions={stackOptions}>
      <Stack.Screen name="screens/OnboardingScreen" />
      {/* <Stack.Screen name="screens/CreateAccountScreen" /> */}
      <Stack.Screen name="screens/MapScreen" />
      <Stack.Screen name="screens/SettingsScreen" />
      {/* <Stack.Screen name="screens/AlertDetailsScreen" />
      <Stack.Screen name="screens/PlanTripScreen" /> */}
    </Stack>
  );
}
